import { useEffect, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';

import styles from '../styles/Home.module.scss';

import LsqGrid from '../_components/lsq-grid';
import Link from 'next/link';
import { useRouter } from 'next/router';
import axios from 'axios';

export default function Home() {
  const router = useRouter();

  const [rows, setRows] = useState([]);
  const [cols, setCols] = useState([]);

  useEffect(() => {
    const getUsers = async () => {
      try {
        const usersRes = await axios.get(
          'http://jsonplaceholder.typicode.com/todos?_start=0&_limit=5',
        );
        const firstUserDataKeys = Object.keys(usersRes.data[0]);

        const dashboardCols = firstUserDataKeys.map((colKey) => ({
          id: colKey,
          displayName: colKey,
        }));

        setTimeout(() => {
          setCols(dashboardCols);

          setRows(usersRes.data);
        }, 2000);
      } catch (error) {
        console.log(error);
      }
    };

    getUsers();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to product dashboard</h1>
        {rows.length > 0 && (
          <LsqGrid
            rows={rows}
            columns={cols}
            rowUniqueId={cols[1]?.id}></LsqGrid>
        )}
        {rows.length === 0 && <p>loading</p>}
        <section className={styles.links}>
          <button type="button" onClick={() => router.push('/second-page?')}>
            Second Page Button
          </button>
          <Link href="/second-page">
            <a>Second Page</a>
          </Link>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer">
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
