import Head from 'next/head';

export default function SecondPage() {
  return (
    <section className="second-page">
      <Head>
        <title>Second page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>this is a second page, believe it or not</main>
      <footer>this is a footer</footer>
    </section>
  );
}
